<div class="page-head">
  <div class="page-title">
    <h1>Create Resource<small> Uniform resource locator.</small></h1>
  </div>
</div>

<ul class="page-breadcrumb breadcrumb">
  <li> <a href="/admin">Administration</a> <i class="fa fa-circle"></i> </li>
  <li> <a href="/admin/resource">Resources</a> <?php if($this->parent_id != 0): ?><i class="fa fa-circle"></i><?php endif; ?> </li>
  <?php $count = 0; ?>
  <?php foreach($this->navigation as $nav): ?>
  <?php $count++ ?>
  <li> <a href="/admin/resource/parent_id/<?php echo $nav['id'] ?>"><?php echo $nav['title'] ?></a><?php if(count($this->navigation) != $count): ?><i class="fa fa-circle"></i><?php endif; ?> </li>
  <?php endforeach; ?>
</ul>

<div class="row">
  <div class="col-md-12">
    <div class="portlet box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-gift"></i>Available Options </div>
      </div>
      <div class="portlet-body form">
        <form action="/admin/resource/create" method="post" class="form-horizontal">
          <?php echo $this->token ?>
          <input type="hidden" name="parent_id" value="<?php echo $this->parent_id ?>" />
          <div class="form-body">
            <div class="form-group">
              <label class="col-md-3 control-label">Title</label>
              <div class="col-md-4">
                <input type="text" name="title" required="required" class="form-control input-circle" placeholder="Resource title." />
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Description</label>
              <div class="col-md-4">
                <textarea name="description" class="form-control" placeholder="Resource description." style="height:200px"></textarea>
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Resource</label>
              <div class="col-md-4">
                <input type="text" name="url" class="form-control input-circle" placeholder="Uniform resource locator." />
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Status</label>
              <div class="col-md-4">
                <select class="form-control" name="status" id="status">
                  <?php foreach($this->statuses as $key => $val): ?>
                  <option value="<?php echo $key ?>"><?php echo $val ?></option>
                  <?php endforeach; ?>
                </select>
              </div>
            </div>
          </div>
          <div class="form-actions">
            <div class="row">
              <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn btn-circle blue">Submit</button>
                <button type="button" class="btn btn-circle default">Cancel</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
