<div class="page-head">
  <div class="page-title">
    <h1>Update Resource<small> Uniform resource locator.</small></h1>
  </div>
</div>

<ul class="page-breadcrumb breadcrumb">
  <li> <a href="/admin">Administration</a> <i class="fa fa-circle"></i> </li>
  <li> <a href="/admin/resource">Resources</a> <i class="fa fa-circle"></i> </li>
  <?php foreach($this->navigation as $nav): ?>
  <li> <a href="/admin/resource/parent_id/<?php echo $nav['id'] ?>"><?php echo $nav['title'] ?></a> <i class="fa fa-circle"></i> </li>
  <?php endforeach; ?>
  <li> <a href="/admin/resource/edit/id/<?php echo $this->id ?>/parent_id/<?php echo $this->parent_id ?>"><?php echo $row->title ?></a> </li>
</ul>

<?php echo $this->partial('admin/messages'); ?>

<div class="row">
  <div class="col-md-12">
    <div class="portlet box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-gift"></i> Available Options </div>
      </div>
      <div class="portlet-body form">
        <form action="/admin/resource/edit" method="post" class="form-horizontal">
          <?php echo $this->token ?>
          <input type="hidden" name="id" value="<?php echo $this->id ?>" />
          <input type="hidden" name="parent_id" value="<?php echo $this->parent_id ?>" />
          <div class="form-body">
            <div class="form-group">
              <label class="col-md-3 control-label">Title</label>
              <div class="col-md-4">
                <input type="text" name="title" required="required" class="form-control input-circle" value="<?php echo $row->title ?>" />
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Description</label>
              <div class="col-md-4">
                <textarea name="description" class="form-control" style="height:200px"><?php echo $row->description ?></textarea>
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Resource</label>
              <div class="col-md-4">
                <input type="text" name="url" class="form-control input-circle" value="<?php echo $row->url ?>" />
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Type</label>
              <div class="col-md-4">
                <select class="form-control" name="node_type" id="node_type">
                  <?php foreach($this->types as $key => $val): ?>
                  <?php $selected = ($this->row->node_type == $key) ? 'selected="selected"': '' ?>
                  <option value="<?php echo $key ?>" <?php echo $selected ?>><?php echo $val ?></option>
                  <?php endforeach; ?>
                </select>
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Status</label>
              <div class="col-md-4">
                <select class="form-control" name="node_status" id="node_status">
                  <?php foreach($this->statuses as $key => $val): ?>
                  <?php $selected = ($this->row->node_status == $key) ? 'selected="selected"': '' ?>
                  <option value="<?php echo $key ?>" <?php echo $selected ?>><?php echo $val ?></option>
                  <?php endforeach; ?>
                </select>
              </div>
            </div>
            <?php if ($this->row->node_type != \Application\Model\Resource::NODE_TYPE_CATEGORY): ?>
            <div class="form-group">
              <label class="col-md-3 control-label">Tags</label>
              <div class="col-md-4">
                <input type="text" name="tags" id="tags" class="form-control input-circle" value="<?php echo $this->tags; ?>" />
              </div>
            </div>
            <?php endif; ?>
          </div>
          <div class="form-actions">
            <div class="row">
              <div class="col-md-offset-3 col-md-9">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="button" class="btn btn-default">Cancel</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
