<div class="page-head">
  <div class="page-title">
    <h1>Resource Management <small>node list model</small></h1>
  </div>
</div>

<ul class="page-breadcrumb breadcrumb">
  <li> <a href="/admin">Administration</a> <i class="fa fa-circle"></i> </li>
  <li> <a href="/admin/resource">Resources</a><?php if(sizeof($this->navigation)): ?><i class="fa fa-circle"><?php endif; ?></i> </li>
  <?php $count = 0; ?>
  <?php foreach($this->navigation as $nav): ?>
  <?php $count++ ?>
  <li> <a href="/admin/resource/parent_id/<?php echo $nav['id'] ?>"><?php echo $nav['title'] ?></a><?php if(count($this->navigation) != $count): ?><i class="fa fa-circle"></i><?php endif; ?> </li>
  <?php endforeach; ?>
</ul>

<?php echo $this->partial('admin/messages'); ?>

<div class="row" id="resources">
  <div class="col-md-12">
    <div class="portlet">
      <div class="portlet-title">
        <div class="caption"> <i class="icon-bar-chart"></i> <span class="caption-subject bold uppercase">Resources Datastore</span> <span class="caption-helper">node management.</span> </div>
        <div class="actions">
          <div class="btn-group"> 
            <a class="btn btn-sm green" href="/admin/resource/create/parent_id/<?php echo $this->parent_id ?>"> Create Resource <i class="fa fa-location-arrow"></i> </a>
          </div>
        </div>
      </div>
      <div class="portlet-body">
        <div class="tabbable-line">
          <ul class="nav nav-tabs">
            <li class="active"> <a href="#overview_1" data-toggle="tab"> Resources </a> </li>
            <li> <a href="#overview_2" data-toggle="tab"> Most Viewed </a> </li>
            <li> <a href="#overview_3" data-toggle="tab"> Branch View </a> </li>
            <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Miscellaneous <i class="fa fa-angle-down"></i> </a>
              <ul class="dropdown-menu" role="menu">
                <li> <a href="#overview_4" tabindex="-1" data-toggle="tab"> Clean Tags </a> </li>
                <li> <a href="#overview_4" tabindex="-1" data-toggle="tab"> Export List </a> </li>
              </ul>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active" id="overview_1">
            
            
        <div class="table-container">
          <div class="table-actions-wrapper"> 
            <span> </span>
            <select class="table-group-action-input form-control input-inline input-small input-sm">
              <option value="">Select...</option>
              <option value="cancel">Cancel</option>
              <option value="hold">Hold</option>
              <option value="on-hold">On Hold</option>
              <option value="close">Close</option>
            </select>
            <button class="btn btn-sm green table-group-action-submit"> <i class="fa fa-check"></i> Submit</button>
          </div>
          <table class="table table-striped table-bordered table-hover table-data-table" id="datatable">
            <thead>
              <tr role="row" class="heading">
                <th width="2%"> <input type="checkbox" class="group-checkable"></th>
                <th width="8%"> ID&nbsp;# </th>
                <th width="30%"> Title </th>
                <th width="15%"> Category </th>
                <th width="15%"> Administrator </th>
                <th width="15%"> Date Created </th>
                <th width="15%"> Actions </th>
              </tr>
              <tr role="row" class="filter">
                <td></td>
                <td>
                  <div class="input-group margin-bottom-5">
                    <input type="text" class="form-control form-filter input-sm" name="id_from" placeholder="From">
                  </div>
                  <div class="input-group">
                    <input type="text" class="form-control form-filter input-sm" name="id_to" placeholder="To">
                  </div>
                </td>
                <td><input type="text" class="form-control form-filter input-sm" name="title" autocomplete="off"></td>
                <td>
                  <select name="category" class="form-control form-filter input-sm">
                    <option value="all">All</option>
                    <?php foreach($this->categories as $category): ?>
                    <option value="<?php echo $category['id']?>"><?php echo $category['title']?></option>
                    <?php endforeach; ?>
                  </select>
                </td>
                <td><input type="text" class="form-control form-filter input-sm" name="username" autocomplete="off"></td>
                <td>
                  <div class="input-group date date-picker margin-bottom-5" data-date-format="yyyy-mm-dd">
                    <input type="text" class="form-control form-filter input-sm" readonly name="created_from" placeholder="From">
                    <span class="input-group-btn">
                      <button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button>
                    </span> 
                  </div>
                  <div class="input-group date date-picker" data-date-format="yyyy-mm-dd">
                    <input type="text" class="form-control form-filter input-sm" readonly name="created_to" placeholder="To">
                    <span class="input-group-btn">
                      <button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button>
                    </span> 
                  </div>
                </td>
                <td>
                  <div class="filter-wrap">
                    <button class="btn btn-sm btn-outline green filter-submit"><i class="fa fa-search"></i> Search</button>
                  </div>
                  <div class="filter-wrap">
                    <button class="btn btn-sm btn-outline red filter-cancel"><i class="fa fa-times"></i> Reset</button>
                  </div>
                </td>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>
        
        
            </div>
            <div class="tab-pane" id="overview_2">
              <div class="table-responsive">
                <table class="table table-striped table-hover table-bordered">
                  <thead>
                    <tr>
                      <th style="width: 92%;"> Resource Information </th>
                      <th style="width: 8%;text-align:center;"> Views </th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php foreach($this->views as $view): ?>
                    <tr>
                      <td><a href="<?php echo $view['url'] ?>" title="<?php echo $view['title'] ?>" target="_blank"> <?php echo $view['title'] ?> </a><br/><?php echo $view['description'] ?> </td>
                      <td style="text-align:center;"> <?php echo $view['views'] ?> </td>
                    </tr>
                    <?php endforeach; ?>
                  </tbody>
                </table>
              </div>
            </div>
            <div class="tab-pane" id="overview_3">
              <div id="tree" class="tree"> </div>
            </div>
            <div class="tab-pane" id="overview_4">
              <div class="table-responsive">
                <table class="table table-striped table-hover table-bordered">
                  <thead>
                    <tr>
                      <th> Customer Name </th>
                      <th> Date </th>
                      <th> Amount </th>
                      <th> Status </th>
                      <th> </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><a href="#"> David Wilson </a></td>
                      <td> 3 Jan, 2013 </td>
                      <td> $625.50 </td>
                      <td><span class="label label-sm label-warning"> Pending </span></td>
                      <td><a href="#" class="btn default btn-xs green-stripe"> View </a></td>
                    </tr>
                    <tr>
                      <td><a href="#"> Amanda Nilson </a></td>
                      <td> 13 Feb, 2013 </td>
                      <td> $12625.50 </td>
                      <td><span class="label label-sm label-warning"> Pending </span></td>
                      <td><a href="#" class="btn default btn-xs green-stripe"> View </a></td>
                    </tr>
                    <tr>
                      <td><a href="#"> Jhon Doe </a></td>
                      <td> 20 Mar, 2013 </td>
                      <td> $125.00 </td>
                      <td><span class="label label-sm label-success"> Success </span></td>
                      <td><a href="#" class="btn default btn-xs green-stripe"> View </a></td>
                    </tr>
                    <tr>
                      <td><a href="#"> Bill Chang </a></td>
                      <td> 29 May, 2013 </td>
                      <td> $12,125.70 </td>
                      <td><span class="label label-sm label-info"> In Process </span></td>
                      <td><a href="#" class="btn default btn-xs green-stripe"> View </a></td>
                    </tr>
                    <tr>
                      <td><a href="#"> Paul Strong </a></td>
                      <td> 1 Jun, 2013 </td>
                      <td> $890.85 </td>
                      <td><span class="label label-sm label-success"> Success </span></td>
                      <td><a href="#" class="btn default btn-xs green-stripe"> View </a></td>
                    </tr>
                    <tr>
                      <td><a href="#"> Jane Hilson </a></td>
                      <td> 5 Aug, 2013 </td>
                      <td> $239.85 </td>
                      <td><span class="label label-sm label-danger"> Canceled </span></td>
                      <td><a href="#" class="btn default btn-xs green-stripe"> View </a></td>
                    </tr>
                    <tr>
                      <td><a href="#"> Patrick Walker </a></td>
                      <td> 6 Aug, 2013 </td>
                      <td> $1239.85 </td>
                      <td><span class="label label-sm label-success"> Success </span></td>
                      <td><a href="#" class="btn default btn-xs green-stripe"> View </a></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
