<div class="page-head">
  <div class="page-title">
    <h1>Dashboard <small>Statistics Overview</small></h1>
  </div>
</div>

<ul class="page-breadcrumb breadcrumb">
  <li> <a href="/admin">Administration</a> <i class="fa fa-circle"></i> </li>
  <li> <a href="/admin">Dashboard</a> </li>
</ul>

<div class="row widget-row">
  <div class="col-md-3">
    <div class="widget-thumb widget-bg-color-white text-uppercase">
      <h4 class="widget-thumb-heading">Current Balance</h4>
      <div class="widget-thumb-wrap"> <i class="bg-green widget-thumb-icon fa fa-bar-chart-o"></i>
        <div class="widget-thumb-body"> <span class="widget-thumb-subtitle">USD</span> <span class="widget-thumb-body-stat" data-counter="counterup" data-value="7,644">7,644</span> </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="widget-thumb widget-bg-color-white text-uppercase">
      <h4 class="widget-thumb-heading">Weekly Sales</h4>
      <div class="widget-thumb-wrap"> <i class="bg-red widget-thumb-icon fa fa-bar-chart-o"></i>
        <div class="widget-thumb-body"> <span class="widget-thumb-subtitle">USD</span> <span class="widget-thumb-body-stat" data-counter="counterup" data-value="1,293">1,293</span> </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="widget-thumb widget-bg-color-white text-uppercase">
      <h4 class="widget-thumb-heading">Biggest Purchase</h4>
      <div class="widget-thumb-wrap"> <i class="bg-purple widget-thumb-icon fa fa-bar-chart-o"></i>
        <div class="widget-thumb-body"> <span class="widget-thumb-subtitle">USD</span> <span class="widget-thumb-body-stat" data-counter="counterup" data-value="815">815</span> </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="widget-thumb widget-bg-color-white text-uppercase">
      <h4 class="widget-thumb-heading">Average Monthly</h4>
      <div class="widget-thumb-wrap"> <i class="bg-blue widget-thumb-icon fa fa-bar-chart-o"></i>
        <div class="widget-thumb-body"> <span class="widget-thumb-subtitle">USD</span> <span class="widget-thumb-body-stat" data-counter="counterup" data-value="5,071">5,071</span> </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption caption-md font-blue"> <i class="fa fa-bar-chart-o font-blue"></i> <span class="caption-subject theme-font bold uppercase">Traffic Statistics: October 1, 2013 - October 31, 2013</span> </div>
      </div>
      <div class="portlet-body">
        <div id="site_activities_loading"> <img src="/img/loading.gif" alt="loading" /> </div>
        <div id="site_activities_content" class="display-none">
          <div id="site_activities" style="height: 228px;"> </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption caption-md font-blue"> <i class="fa fa-bar-chart-o font-blue"></i> <span class="caption-subject theme-font bold uppercase">Recent Activities!</span> </div>
      </div>
      <div class="portlet-body">
        <div class="list-group"> 
          <?php foreach($this->activity as $activity):?>
          <a href="#" class="list-group-item"> <span class="badge"><?php echo $this->TimeFormat($activity['created_at']) ?></span> <i class="fa <?php echo $activity['icon'] ?>"></i> <?php echo $activity['text'] ?> </a> 
          <?php endforeach; ?>
        </div>
        <div class="text-right"> <a href="#">View All Activity <i class="fa fa-arrow-circle-right"></i></a> </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption caption-md font-blue"> <i class="fa fa-bar-chart-o font-blue"></i> <span class="caption-subject theme-font bold uppercase">Top Tags</span> </div>
      </div>
      <div class="portlet-body">
        <div id="top-tags" class="chart" style="height: 350px;"> </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption caption-md font-blue"> <i class="fa fa-bar-chart-o font-blue"></i> <span class="caption-subject theme-font bold uppercase">Recent Activities</span> </div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-striped tablesorter">
            <thead>
              <tr>
                <th>Order # <i class="fa fa-sort"></i></th>
                <th>Order Date <i class="fa fa-sort"></i></th>
                <th>Order Time <i class="fa fa-sort"></i></th>
                <th>Amount (USD) <i class="fa fa-sort"></i></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>3326</td>
                <td>10/21/2013</td>
                <td>3:29 PM</td>
                <td>$321.33</td>
              </tr>
              <tr>
                <td>3325</td>
                <td>10/21/2013</td>
                <td>3:20 PM</td>
                <td>$234.34</td>
              </tr>
              <tr>
                <td>3324</td>
                <td>10/21/2013</td>
                <td>3:03 PM</td>
                <td>$724.17</td>
              </tr>
              <tr>
                <td>3323</td>
                <td>10/21/2013</td>
                <td>3:00 PM</td>
                <td>$23.71</td>
              </tr>
              <tr>
                <td>3322</td>
                <td>10/21/2013</td>
                <td>2:49 PM</td>
                <td>$8345.23</td>
              </tr>
              <tr>
                <td>3321</td>
                <td>10/21/2013</td>
                <td>2:23 PM</td>
                <td>$245.12</td>
              </tr>
              <tr>
                <td>3320</td>
                <td>10/21/2013</td>
                <td>2:15 PM</td>
                <td>$5663.54</td>
              </tr>
              <tr>
                <td>3319</td>
                <td>10/21/2013</td>
                <td>2:13 PM</td>
                <td>$943.45</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="text-right"> <a href="#">View All Transactions <i class="fa fa-arrow-circle-right"></i></a> </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption caption-md font-blue"> <i class="fa fa-bar-chart-o font-blue"></i> <span class="caption-subject theme-font bold uppercase">Traffic Statistics: October 1, 2013 - October 31, 2013</span> </div>
      </div>
      <div class="portlet-body">
        <div id="chart_1" class="chart" style="height: 500px;"> </div>
      </div>
    </div>
  </div>
</div>
