<div class="page-head">
  <div class="page-title">
    <h1>Dashboard <small>Statistics Overview</small></h1>
  </div>
</div>

<ul class="page-breadcrumb breadcrumb">
  <li> <a href="/admin">Administration</a> <i class="fa fa-circle"></i> </li>
  <li> <a href="/admin">Dashboard</a> </li>
</ul>

<div class="row widget-row">
  <div class="col-md-3">
    <div class="widget-thumb widget-bg-color-white text-uppercase">
      <h4 class="widget-thumb-heading">Total Categories</h4>
      <div class="widget-thumb-wrap"> <i class="bg-green widget-thumb-icon fa fa-bar-chart-o"></i>
        <div class="widget-thumb-body"> <span class="widget-thumb-subtitle">COUNT</span> <span class="widget-thumb-body-stat total_categories" data-counter="counterup" data-value="0">0</span> </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="widget-thumb widget-bg-color-white text-uppercase">
      <h4 class="widget-thumb-heading">Total Resources</h4>
      <div class="widget-thumb-wrap"> <i class="bg-red widget-thumb-icon fa fa-bar-chart-o"></i>
        <div class="widget-thumb-body"> <span class="widget-thumb-subtitle">COUNT</span> <span class="widget-thumb-body-stat total_resources" data-counter="counterup" data-value="0">0</span> </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="widget-thumb widget-bg-color-white text-uppercase">
      <h4 class="widget-thumb-heading">Resource Views</h4>
      <div class="widget-thumb-wrap"> <i class="bg-purple widget-thumb-icon fa fa-bar-chart-o"></i>
        <div class="widget-thumb-body"> <span class="widget-thumb-subtitle">TOTAL</span> <span class="widget-thumb-body-stat total_views" data-counter="counterup" data-value="0">0</span> </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="widget-thumb widget-bg-color-white text-uppercase">
      <h4 class="widget-thumb-heading">Total Tags</h4>
      <div class="widget-thumb-wrap"> <i class="bg-blue widget-thumb-icon fa fa-bar-chart-o"></i>
        <div class="widget-thumb-body"> <span class="widget-thumb-subtitle">COUNT</span> <span class="widget-thumb-body-stat total_tags" data-counter="counterup" data-value="0">0</span> </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption caption-md font-blue"> 
          <i class="fa fa-bar-chart-o font-blue"></i> 
          <span class="caption-subject theme-font bold uppercase">Monthly Activity</span> 
        </div>
      </div>
      <div class="portlet-body">
        <div id="monthly_activity_loading"> <img src="/img/loading.gif" alt="loading" /> </div>
        <div id="monthly_activity_content" class="display-none">
          <div id="monthly_activity" style="height: 228px;"> </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption caption-md font-blue"> 
          <i class="fa fa-bar-chart-o font-blue"></i> 
          <span class="caption-subject theme-font bold uppercase">Recent Activity</span> 
        </div>
      </div>
      <div class="portlet-body">
        <div class="list-group"> 
          <?php foreach($this->activity as $activity):?>
          <a href="#" class="list-group-item"> <span class="badge"><?php echo $this->TimeFormat($activity['created_at']) ?></span> <i class="fa <?php echo $activity['icon'] ?>"></i> <?php echo $activity['text'] ?> </a> 
          <?php endforeach; ?>
        </div>
        <div class="text-right"> <a href="/admin/activity">View All Activity <i class="fa fa-arrow-circle-right"></i></a> </div>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption caption-md font-blue"> 
          <i class="fa fa-bar-chart-o font-blue"></i> 
          <span class="caption-subject theme-font bold uppercase">Top Tags</span> 
        </div>
      </div>
      <div class="portlet-body">
        <div id="top-tags" class="chart" style="height: 430px;"> </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="portlet light">
      <div class="portlet-title">
        <div class="caption caption-md font-blue"> 
          <i class="fa fa-bar-chart-o font-blue"></i> 
          <span class="caption-subject theme-font bold uppercase">Yearly Activity</span> 
        </div>
      </div>
      <div class="portlet-body">
        <div id="yearly_activity" class="chart" style="height: 500px;"> </div>
      </div>
    </div>
  </div>
</div>
