<?php if ($this->flashMessenger()->getMessages()): ?>
  <?php foreach ($this->flashMessenger()->getMessages() as $message): ?>
  <div class="alert alert-success display-hide" style="display:block;">
  <button class="close" data-close="alert"></button>
  <p><?php echo $message ?></p>
</div>
  <?php endforeach; ?>
<?php elseif ($this->flashMessenger()->getErrorMessages()): ?>
<div class="alert alert-danger display-hide" style="display:block;">
  <button class="close" data-close="alert"></button>
  <?php foreach ($this->flashMessenger()->getErrorMessages() as $message): ?>
  <p><?php echo $message ?></p>
  <?php endforeach; ?>
</div>
<?php elseif ($this->flashMessenger()->getInfoMessages()): ?>
<div class="alert alert-success display-hide" style="display:block;">
  <button class="close" data-close="alert"></button>
  <?php foreach ($this->flashMessenger()->getInfoMessages() as $message): ?>
  <p><?php echo $message ?></p>
  <?php endforeach; ?>
</div>
<?php elseif ($this->flashMessenger()->getWarningMessages()): ?>
<div class="alert alert-danger display-hide" style="display:block;">
  <button class="close" data-close="alert"></button>
  <?php foreach ($this->flashMessenger()->getWarningMessages() as $message): ?>
  <p><?php echo $message ?></p>
  <?php endforeach; ?>
</div>
<?php endif; ?>