<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"> 

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"> 
      <span class="sr-only">Toggle navigation</span> 
      <span class="icon-bar"></span> 
      <span class="icon-bar"></span> 
      <span class="icon-bar"></span> 
    </button>
    <a class="navbar-brand" href="/admin">Resources Administration</a> 
  </div>
  
  <div class="collapse navbar-collapse navbar-ex1-collapse">
  
    <!--<ul class="nav navbar-nav side-nav">
      <li class="active"><a href="/admin"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li><a href="/admin/resource"><i class="fa fa-bar-chart-o"></i> Resources</a></li>
    </ul>-->
    
    <ul class="nav navbar-nav navbar-right navbar-user">
      
      <li><a href="/admin/user">Users</a></li>
      <li><a href="/admin/activity">Activity</a></li>
      <li><a href="/admin/resource">Resources</a></li>
      
      <li class="dropdown user-dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $auth->username ?> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="/"><i class="fa fa-user"></i> Search</a></li>
          <li><a href="/admin/settings"><i class="fa fa-gear"></i> Settings</a></li>
          <li class="divider"></li>
          <li><a href="/logout"><i class="fa fa-power-off"></i> Log Out</a></li>
        </ul>
      </li>
      
    </ul>
  </div>
</nav>
