<form class="form-signin" action="/login" method="post">
  <?php echo $this->token ?>
  <h2 class="form-signin-heading">Please sign in</h2>
  <label for="email" class="sr-only">Email address</label>
  <input type="email" name="email" id="email" class="form-control" placeholder="Email" autocomplete="off" required autofocus>
  <label for="password" class="sr-only">Password</label>
  <input type="password" name="password" id="password"  class="form-control" placeholder="Password" required>
  <div class="checkbox">
    <label> <input type="checkbox" name="remember" value="remember"> Remember me </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>
