<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta content="" name="description" />
<meta content="" name="author" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Resources Datastore</title>
<?php echo $this->headTitle() ?>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans:400,700" type="text/css" media="all" />
<link href="/css/style.min.css" rel="stylesheet">
<?php echo $this->headLink() ?>
</head>
<body>

<div class="container">
  <?php echo $this->content ?>
</div>

<script src="/js/script.js"></script>
<?php echo $this->inlineScript() ?>

</body>
</html>
