<div class="page-head">
  <div class="page-title">
    <h1>Activity Management<small> system activity logs</small></h1>
  </div>
</div>

<ul class="page-breadcrumb breadcrumb">
  <li> <a href="/admin">Administration</a> <i class="fa fa-circle"></i> </li>
  <li> <a href="/admin/activity">Activity</a></li>
</ul>

<?php echo $this->partial('admin/messages'); ?>

<div class="row" id="resources">
  <div class="col-md-12">
    <div class="portlet">
      <div class="portlet-title">
        <div class="caption"> 
          <i class="icon-bar-chart"></i> 
          <span class="caption-subject bold uppercase">System Activity</span> 
          <span class="caption-helper">Activity Management.</span> 
        </div>
      </div>
      <div class="portlet-body">
        <div class="table-container">
          <div class="table-actions-wrapper"> 
            <span> </span>
            <select class="table-group-action-input form-control input-inline input-small input-sm">
              <option value="">Select...</option>
              <option value="mark-delete">Delete Selected</option>
            </select>
            <button class="btn btn-sm green table-group-action-submit"> <i class="fa fa-check"></i> Submit</button>
          </div>
          <table class="table table-striped table-bordered table-hover table-data-table" id="datatable">
            <thead>
              <tr role="row" class="heading">
                <th width="2%"> <input type="checkbox" class="group-checkable"></th>
                <th width="8%"> ID&nbsp;# </th>
                <th width="50%"> Text </th>
                <th width="15%"> Username </th>
                <th width="15%"> Created </th>
                <th width="10%"> Actions </th>
              </tr>
              <tr role="row" class="filter">
                <td></td>
                <td>
                  <div class="input-group margin-bottom-5">
                    <input type="text" class="form-control form-filter input-sm" name="id_from" placeholder="From">
                  </div>
                  <div class="input-group">
                    <input type="text" class="form-control form-filter input-sm" name="id_to" placeholder="To">
                  </div>
                </td>
                <td><input type="text" class="form-control form-filter input-sm" name="text" autocomplete="off"></td>
                <td><input type="text" class="form-control form-filter input-sm" name="username" placeholder="Username"></td>
                <td>
                  <div class="input-group date date-picker margin-bottom-5" data-date-format="yyyy-mm-dd">
                    <input type="text" class="form-control form-filter input-sm" readonly name="created_from" placeholder="From">
                    <span class="input-group-btn">
                      <button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button>
                    </span> 
                  </div>
                  <div class="input-group date date-picker" data-date-format="yyyy-mm-dd">
                    <input type="text" class="form-control form-filter input-sm" readonly name="created_to" placeholder="To">
                    <span class="input-group-btn">
                      <button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button>
                    </span> 
                  </div>
                </td>
                <td>
                  <div class="filter-wrap">
                    <button class="btn btn-sm btn-outline green filter-submit"><i class="fa fa-search"></i> Search</button>
                  </div>
                  <div class="filter-wrap">
                    <button class="btn btn-sm btn-outline red filter-cancel"><i class="fa fa-times"></i> Reset</button>
                  </div>
                </td>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
