<div class="page-head">
  <div class="page-title">
    <h1>Activity Information<small> View Activity.</small></h1>
  </div>
</div>

<ul class="page-breadcrumb breadcrumb">
  <li> <a href="/admin">Administration</a> <i class="fa fa-circle"></i> </li>
  <li> <a href="/admin/activity">Activity</a> <i class="fa fa-circle"></i> </li>
  <li> <a href="/admin/activity/view/id/<?php echo $this->row->id ?>"><?php echo $row->text ?></a> </li>
</ul>

<?php echo $this->partial('admin/messages'); ?>

<div class="row">
  <div class="col-md-12">
    <div class="portlet box">
      <div class="portlet-title">
        <div class="caption"> <i class="fa fa-gift"></i> Activity Information </div>
      </div>
      <div class="portlet-body form">
        <form action="/admin/resource/edit" method="post" class="form-horizontal">
          <?php echo $this->token ?>
          <input type="hidden" name="id" value="<?php echo $this->id ?>" />
          <input type="hidden" name="parent_id" value="<?php echo $this->parent_id ?>" />
          <div class="form-body">
            <div class="form-group">
              <label class="col-md-3 control-label">Text</label>
              <div class="col-md-4">
                <input type="text" name="text" required="required" class="form-control input-circle" value="<?php echo $row->text ?>" />
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">IP Address</label>
              <div class="col-md-4">
                <input type="text" name="ip_address" required="required" class="form-control input-circle" value="<?php echo \Application\Model\Activity::decodeIp($row->ip_address) ?>" />
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Date</label>
              <div class="col-md-4">
                <input type="text" name="created_At" required="required" class="form-control input-circle" value="<?php echo date('l, F jS Y g:i a', strtotime($row->created_at)) ?>" />
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
