<?php echo $this->placeholder('header'); ?>
  
<section class="main-content">
  <div class="row margin-top-10">
    <table class="table table-striped table-bordered table-hover" id="datatable">
      <thead>
        <tr class="heading">
          <th width="10%"> ID&nbsp;# </th>
          <th width="35%"> Title </th>
          <th width="20%"> Category </th>
          <th width="20%"> Created </th>
          <th width="15%"> Actions </th>
        </tr>
        <tr class="filter">
          <td>
            <div class="input-group margin-bottom-5">
              <input type="text" class="form-control form-filter input-sm" name="id_from" placeholder="From">
            </div>
            <div class="input-group">
              <input type="text" class="form-control form-filter input-sm" name="id_to" placeholder="To">
            </div>
          </td>
          <td><input type="text" class="form-control form-filter input-sm" name="title" autocomplete="off"></td>
          <td>
            <select name="category" class="form-control form-filter input-sm">
              <option value="all">All</option>
              <?php foreach($this->categories as $category): ?>
              <option value="<?php echo $category['id']?>"><?php echo $category['title']?></option>
              <?php endforeach; ?>
            </select>
          </td>
          <td>
            <div class="input-group date date-picker margin-bottom-5" data-date-format="yyyy-mm-dd">
              <input type="text" class="form-control form-filter input-sm" readonly name="created_from" placeholder="From">
              <span class="input-group-btn"><button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button></span> 
            </div>
            <div class="input-group date date-picker" data-date-format="yyyy-mm-dd">
              <input type="text" class="form-control form-filter input-sm" readonly name="created_to" placeholder="To">
              <span class="input-group-btn"><button class="btn btn-sm default" type="button"><i class="fa fa-calendar"></i></button></span> 
            </div>
          </td>
          <td>
            <div class="margin-bottom-5">
              <button class="btn btn-sm yellow filter-submit margin-bottom"><i class="fa fa-search"></i> Search</button>
            </div>
            <div class="margin-bottom-5">
              <button class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Reset</button>
            </div>
          </td>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</section>
